rime.so:rime.c
	cc rime.c -shared -fPIC -I/nix/store/m7ljp75773z9pn6jj5phnkbsnbbkqq6s-luajit-2.1.1713773202/include -L/nix/store/m7ljp75773z9pn6jj5phnkbsnbbkqq6s-luajit-2.1.1713773202/lib -I${RIME_DIR}/include -L${RIME_DIR}/lib/ -lluajit-5.1 -lrime -o rime.so
